Adjusting create to show password name as input
I was working on a response to a ticket and noticed the `create` sub-command mentioned taking the `PASSWORD_ID` as input which didn't make sense since it couldn't have an ID yet since it hasn't been created, so just to confirm I went ahead and ran a quick test from the CLI to see how its output looks to share here for reference:

```
> pscale password create test-database main --org=example
Error: missing argument <name>

Usage:
  pscale password create <database> <branch> <name> [flags]
```

I just made the minor adjustment but if any extra text is desirable to describe that `<PASSWORD_NAME>`is a friendly name for the user to use as a reference only that can be added in before merging.